Object.assign(window.portfolioContent.zh,{"cvMetric1": "参与概念与定位的项目", "cvMetric2": "进入实施阶段的项目", "aboutText": "我将早期想法转化为清晰的概念、故事和体验，结合研究、策略思考、视觉方向与跨团队协作，推动项目从最初提案走向执行。", "aboutNote": "过去十余年，我的工作覆盖生活方式、酒店与体验型项目，将新兴趋势、用户需求和商业机会转化为能够被理解、认同并付诸实践的想法。", "workNote": "从存量资产重新定位，到新体验的策划与运营：通过三个项目了解我的具体贡献。", "archiveLabel": "04 / 更多项目贡献", "archiveNote": "涵盖旧空间改造与活动品牌表达的其他项目。", "caseLabel": "精选项目 / 我的贡献", "caseIntro": "以下内容来自我的实际项目经历。", "experienceText": "以城市发展研究为起点，逐步深入概念策划、体验策略与跨团队交付。", "date0": "2016年7月—2026年2月 · 北京", "role0": "概念策划与体验策略负责人", "expand0": "职责与贡献", "job0_0": "参与40余个生活方式、酒店、商业及体验型项目的概念与定位，其中10余个进入实施阶段。", "job0_1": "建立涵盖项目诊断、定位、命名、叙事、用户画像、标杆案例、空间分区及体验场景的完整提案。", "job0_2": "直接与CEO研究新消费业态及新业务，将研究转化为设计、品牌、招商和运营团队可使用的任务简报。", "job0_3": "面向政府、企业高管、资产方及投资人制作并汇报提案，准备英文材料与讲稿，接待国际项目考察。", "job0_4": "协同财务测算、设计、品牌、招商和运营团队，审视实施方案是否延续原有定位与体验方向。", "date1": "2015年1月—2016年7月 · 北京", "role1": "城市发展顾问", "expand1": "职责与贡献", "job1_0": "为城市及区域发展项目进行政策、市场与项目研究，参与可行性研究、投资建议、项目规划及客户汇报。", "job1_1": "通过研究、双语材料及跨文化沟通，支持马达加斯加国家新经济倡议和卡拉卡哈尔中巴经济合作区等国际项目。", "edu": "教育背景", "edu1": "阿伯丁大学 · 房地产硕士 · 2013–2014", "edu2": "伦敦艺术大学切尔西艺术学院 · 室内与空间设计学士 · 2010–2013", "langs": "12年英国教育与生活经历。中文母语；英语流利，可作为专业工作语言。", "tools": "工具：Microsoft Office（精通PowerPoint）、Canva、Photoshop、Illustrator及CapCut。", "contactText": "现居北京。欢迎通过邮件或LinkedIn联系，交流项目及职业机会。", "guideNote": "了解我的经历、项目与能力。此入口目前提供页面导览，尚未接入AI对话。", "guideWork": "查看精选项目 ↗", "guideContact": "联系 Yuchen ↗"});
window.portfolioContent.cases=[{"type": "space", "en": "Repositioning an ageing hotel", "zh": "为老酒店建立新定位", "tagEn": "GUOMAO@5LMEET", "tagZh": "GUOMAO@5LMEET", "steps": [["Challenge", "挑战", "Reposition the former China World Hotel as a lifestyle and social destination.", "将原国贸饭店重新定位为生活方式与社交目的地。"], ["My contribution", "我的贡献", "Developed the “CBD Urban Living Room” concept through market differentiation, user analysis and spatial scenarios.", "通过市场差异化、用户分析和空间场景，形成“CBD城市会客厅”概念。"], ["Project application", "项目应用", "The concept supported renovation, design and operation discussions.", "概念为更新改造、设计和运营讨论提供方向。"]]}, {"type": "brand", "en": "From abandoned farm to community", "zh": "从废弃农场到体验社群", "tagEn": "CAMP WOW", "tagZh": "CAMP WOW", "steps": [["Challenge", "挑战", "Develop a 160-mu (approximately 26-acre) abandoned farm into an experience-led destination.", "为160亩废弃农场建立体验型目的地定位。"], ["My contribution", "我的贡献", "Led the project from concept through day-to-day operation, defining positioning, brand and membership experience and coordinating a 10+ person on-site team.", "从概念推进至日常运营，定义定位、品牌及会员体验，协同10余人的现场团队。"], ["Delivery", "执行成果", "Built a community of several hundred members and delivered 100+ activities annually for families, schools and corporate clients including BMW and Xiaomi.", "建立数百名会员的社群，每年为家庭、学校及包括宝马、小米在内的企业客户开展100余场活动。"]]}, {"type": "story", "en": "Bringing work and life together", "zh": "让工作与生活相互连接", "tagEn": "DONGSI@5LMEET", "tagZh": "DONGSI@5LMEET", "steps": [["Challenge", "挑战", "Help transform a former sauce factory into an early work-live lifestyle community with apartments, commercial space and coworking.", "参与将原酱油厂转化为融合公寓、商业与共享办公的早期工作生活社区。"], ["My contribution", "我的贡献", "Contributed experience direction, furniture and soft-furnishing selection, and post-opening content ideas.", "参与体验方向、家具与软装选配，以及开业后的内容构想。"]]}];
window.portfolioContent.archive=[["decks", "deck", "Nanyang Theatre", "南阳剧场"], ["identity", "identity", "UTP100", "UTP100"]];
window.portfolioContent.archiveDescriptions=[["Concept, spatial and visual direction, and furnishing choices for an old-theatre mixed-use project.", "为旧剧场综合改造项目贡献概念、空间与视觉方向，以及家具陈设选配。"], ["Brand concept, visual materials, signage and on-site expression for a 100 km endurance event connected with Beijing parks.", "为串联北京公园的100公里耐力活动贡献品牌概念、视觉物料、标识与现场表达。"]];
window.portfolioContent.cvBacked=true;

Object.assign(window.portfolioContent.zh,{workLabel:'03 / 作品',workTitle:'让想法逐渐清晰。',workNote:'从概念、空间与品牌，到让它们被理解和实现的各种表达。按工作类型浏览。',labLabel:'04 / AI 实验室',experienceLabel:'05 / 职业旅程',contactLabel:'06 / 下一次对话'});
window.portfolioContent.workCategories=[['all','All Work','全部作品'],['concept','Concept Planning','概念策划'],['realization','0–1 Realization','从零到一'],['visual','Branding & Visual','品牌与视觉'],['proposals','Presentations & Proposals','提案与招商'],['personal','Personal Explorations','个人探索']];
window.portfolioContent.cases[0].category='concept';
window.portfolioContent.cases[1].category='realization';
window.portfolioContent.cases[2].category='concept';
window.portfolioContent.cases.push({"category": "concept", "tagEn": "Nanyang Theatre", "tagZh": "南阳剧场", "en": "Reimagining an old theatre", "zh": "旧剧场的新构想", "collection": false, "steps": [["My contribution", "我的贡献", "Concept, spatial and visual direction, and furnishing choices for an old-theatre mixed-use project.", "为旧剧场综合改造项目贡献概念、空间与视觉方向，以及家具陈设选配。"]]});
window.portfolioContent.cases.push({"category": "visual", "tagEn": "UTP100", "tagZh": "UTP100", "en": "An identity across 100 kilometres", "zh": "贯穿100公里的品牌表达", "collection": false, "steps": [["My contribution", "我的贡献", "Brand concept, visual materials, signage and on-site expression for a 100 km endurance event connected with Beijing parks.", "为串联北京公园的100公里耐力活动贡献品牌概念、视觉物料、标识与现场表达。"]]});
window.portfolioContent.cases.push({"category": "visual", "tagEn": "Posters", "tagZh": "海报", "en": "Poster design", "zh": "海报设计", "collection": true, "steps": [["Overview", "作品概览", "A collection of poster work. Individual pieces and project context are being assembled.", "海报作品集合，具体作品与项目背景正在整理。"]]});
window.portfolioContent.cases.push({"category": "visual", "tagEn": "Merchandise", "tagZh": "衍生品", "en": "Objects & merchandise", "zh": "物件与衍生品", "collection": true, "steps": [["Overview", "作品概览", "A collection of merchandise design. Individual pieces and project context are being assembled.", "衍生品设计集合，具体作品与项目背景正在整理。"]]});
window.portfolioContent.cases.push({"category": "proposals", "tagEn": "Event sponsorship", "tagZh": "赛事招商", "en": "Sponsorship brochures & proposals", "zh": "赛事招商手册与提案", "collection": true, "steps": [["Overview", "作品概览", "Event sponsorship materials and proposal work. Individual documents and project context are being assembled.", "赛事招商材料与提案作品，具体文件与项目背景正在整理。"]]});
window.portfolioContent.cases.push({"category": "personal", "tagEn": "Personal work", "tagZh": "个人作品", "en": "Independent design explorations", "zh": "个人设计探索", "collection": true, "steps": [["Overview", "作品概览", "A collection of personal design work. Individual pieces and their stories are being assembled.", "个人设计作品集合，具体作品及创作故事正在整理。"]]});

Object.assign(window.portfolioContent.cases.find(item=>item.tagEn==='UTP100'),{image:'assets/utp100-visual-system.jpg',imageAltEn:'UTP100 event visual system: apparel, bags, wayfinding, race bibs and event signage',imageAltZh:'UTP100赛事视觉系统：服装、手袋、导视、号码布及现场标识'});

Object.assign(window.portfolioContent.cases.find(item=>item.tagEn==='CAMP WOW'),{"image": "assets/camp-wow/camp-wow-64.jpg", "imageAltEn": "CAMP WOW golden wheat field", "imageAltZh": "CAMP WOW金色麦田", "galleryGroups": [{"en": "Scenery", "zh": "风景", "images": [{"src": "assets/camp-wow/camp-wow-64.jpg", "altEn": "Golden wheat field", "altZh": "金色麦田"}, {"src": "assets/camp-wow/camp-wow-62.jpg", "altEn": "Vegetable garden", "altZh": "蔬菜花园"}, {"src": "assets/camp-wow/camp-wow-44.jpg", "altEn": "Garden dining setting", "altZh": "花园用餐空间"}]}, {"en": "Before & after", "zh": "改造前后", "images": [{"src": "assets/camp-wow/camp-wow-40.jpg", "altEn": "Garden and site renovation comparison", "altZh": "花园与场地改造对比"}, {"src": "assets/camp-wow/camp-wow-42.jpg", "altEn": "Courtyard before and after renovation", "altZh": "庭院改造前后"}, {"src": "assets/camp-wow/camp-wow-41.jpg", "altEn": "Restored interior and artwork installation", "altZh": "室内更新与艺术陈设"}, {"src": "assets/camp-wow/camp-wow-46.jpg", "altEn": "Completed interior details", "altZh": "改造后的室内细节"}]}, {"en": "Activities", "zh": "活动", "images": [{"src": "assets/camp-wow/camp-wow-49.jpg", "altEn": "Family wheat harvest", "altZh": "亲子麦田收割"}, {"src": "assets/camp-wow/camp-wow-52.jpg", "altEn": "Outdoor gathering beside the wheat field", "altZh": "麦田旁的户外活动"}, {"src": "assets/camp-wow/camp-wow-51.jpg", "altEn": "Children exploring the creek", "altZh": "儿童溪水探索"}, {"src": "assets/camp-wow/camp-wow-43.jpg", "altEn": "School group meal", "altZh": "学校团体用餐"}, {"src": "assets/camp-wow/camp-wow-61.jpg", "altEn": "Indoor curling activity", "altZh": "室内冰壶活动"}, {"src": "assets/camp-wow/camp-wow-45.jpg", "altEn": "Birthday dining setup", "altZh": "生日聚餐布置"}, {"src": "assets/camp-wow/camp-wow-53.jpg", "altEn": "Outdoor barbecue", "altZh": "户外烧烤"}, {"src": "assets/camp-wow/camp-wow-48.jpg", "altEn": "Strawberry harvest", "altZh": "草莓采摘"}]}, {"en": "Merchandise", "zh": "衍生品", "images": [{"src": "assets/camp-wow/camp-wow-50.jpg", "altEn": "Branded cap", "altZh": "品牌帽子"}, {"src": "assets/camp-wow/camp-wow-54.jpg", "altEn": "WOW bags", "altZh": "WOW手袋"}, {"src": "assets/camp-wow/camp-wow-59.jpg", "altEn": "Membership card and packaging", "altZh": "会员卡与包装"}]}, {"en": "Design", "zh": "设计", "images": [{"src": "assets/camp-wow/camp-wow-58.jpg", "altEn": "Sweatshirt graphic design", "altZh": "卫衣图案设计"}, {"src": "assets/camp-wow/camp-wow-63.jpg", "altEn": "Hoodie design", "altZh": "连帽卫衣设计"}, {"src": "assets/camp-wow/camp-wow-60.jpg", "altEn": "People and pet illustrations", "altZh": "人物与宠物插画"}]}]});
